<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<DocumentationFile>$(AssemblyName).xml</DocumentationFile>
		<NoWarn>1591</NoWarn>
	</PropertyGroup>

	<!-- References -->

</Project>